# Generated by Django 4.2.30 on 2026-07-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_role_options_role_description_and_more'),
        ('accounts', '0002_alter_profile_options_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='permissions.role'),
        ),
    ]
