# Generated by Django 4.2.30 on 2026-07-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پایپ\u200cلاین')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'پایپ\u200cلاین',
                'verbose_name_plural': 'پایپ\u200cلاین\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('probability', models.PositiveIntegerField(default=0, help_text='درصد احتمال بسته شدن معامله در این مرحله (0 تا 100)')),
                ('is_won', models.BooleanField(default=False, verbose_name='مرحله برد')),
                ('is_lost', models.BooleanField(default=False, verbose_name='مرحله باخت')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='deals.pipeline')),
            ],
            options={
                'verbose_name': 'مرحله',
                'verbose_name_plural': 'مراحل',
                'ordering': ['pipeline', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان معامله')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ')),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تخمینی بسته\u200cشدن')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='contacts.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='contacts.contact')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='مسئول معامله')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='deals.pipeline')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='deals.stage')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
                'ordering': ['-created_at'],
            },
        ),
    ]
