# Generated by Django 4.2.30 on 2026-07-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_profile_role'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='UserFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('own', 'فقط خودش'), ('team', 'تیم'), ('all', 'همه')], default='own', max_length=10)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='permissions.feature')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'feature')},
            },
        ),
    ]
